install:
	bundle install

setup:
	bundle exec setup

start:
	bundle exec dev

console:
	bundle exec rails console

migrate:
	bundle exec rails db:migrate

test:
	NODE_ENV=test bundle exec rails test

.PHONY: test
